version: '1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
