// Code generated by protoc-gen-go. DO NOT EDIT.
// source: satcom.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// position, including latitude and longitude
type LLPosition struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,3,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LLPosition) Reset()         { *m = LLPosition{} }
func (m *LLPosition) String() string { return proto.CompactTextString(m) }
func (*LLPosition) ProtoMessage()    {}
func (*LLPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{0}
}

func (m *LLPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LLPosition.Unmarshal(m, b)
}
func (m *LLPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LLPosition.Marshal(b, m, deterministic)
}
func (m *LLPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LLPosition.Merge(m, src)
}
func (m *LLPosition) XXX_Size() int {
	return xxx_messageInfo_LLPosition.Size(m)
}
func (m *LLPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_LLPosition.DiscardUnknown(m)
}

var xxx_messageInfo_LLPosition proto.InternalMessageInfo

func (m *LLPosition) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *LLPosition) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *LLPosition) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

// position, including latitude, longitude and altitude
type LLAPosition struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Alt                  float32  `protobuf:"fixed32,2,opt,name=alt,proto3" json:"alt,omitempty"`
	Lat                  float32  `protobuf:"fixed32,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,4,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LLAPosition) Reset()         { *m = LLAPosition{} }
func (m *LLAPosition) String() string { return proto.CompactTextString(m) }
func (*LLAPosition) ProtoMessage()    {}
func (*LLAPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{1}
}

func (m *LLAPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LLAPosition.Unmarshal(m, b)
}
func (m *LLAPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LLAPosition.Marshal(b, m, deterministic)
}
func (m *LLAPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LLAPosition.Merge(m, src)
}
func (m *LLAPosition) XXX_Size() int {
	return xxx_messageInfo_LLAPosition.Size(m)
}
func (m *LLAPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_LLAPosition.DiscardUnknown(m)
}

var xxx_messageInfo_LLAPosition proto.InternalMessageInfo

func (m *LLAPosition) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *LLAPosition) GetAlt() float32 {
	if m != nil {
		return m.Alt
	}
	return 0
}

func (m *LLAPosition) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *LLAPosition) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

// utils
// target position
type TargetInfo struct {
	TargetName           string       `protobuf:"bytes,1,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	TargetPosition       *LLAPosition `protobuf:"bytes,2,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TargetInfo) Reset()         { *m = TargetInfo{} }
func (m *TargetInfo) String() string { return proto.CompactTextString(m) }
func (*TargetInfo) ProtoMessage()    {}
func (*TargetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{2}
}

func (m *TargetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetInfo.Unmarshal(m, b)
}
func (m *TargetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetInfo.Marshal(b, m, deterministic)
}
func (m *TargetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetInfo.Merge(m, src)
}
func (m *TargetInfo) XXX_Size() int {
	return xxx_messageInfo_TargetInfo.Size(m)
}
func (m *TargetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TargetInfo proto.InternalMessageInfo

func (m *TargetInfo) GetTargetName() string {
	if m != nil {
		return m.TargetName
	}
	return ""
}

func (m *TargetInfo) GetTargetPosition() *LLAPosition {
	if m != nil {
		return m.TargetPosition
	}
	return nil
}

// represents a zone on earth, using the upper left and bottom right point
type ZoneInfo struct {
	UpperLeft            *LLPosition `protobuf:"bytes,2,opt,name=upper_left,json=upperLeft,proto3" json:"upper_left,omitempty"`
	BottomRight          *LLPosition `protobuf:"bytes,3,opt,name=bottom_right,json=bottomRight,proto3" json:"bottom_right,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ZoneInfo) Reset()         { *m = ZoneInfo{} }
func (m *ZoneInfo) String() string { return proto.CompactTextString(m) }
func (*ZoneInfo) ProtoMessage()    {}
func (*ZoneInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{3}
}

func (m *ZoneInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneInfo.Unmarshal(m, b)
}
func (m *ZoneInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneInfo.Marshal(b, m, deterministic)
}
func (m *ZoneInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneInfo.Merge(m, src)
}
func (m *ZoneInfo) XXX_Size() int {
	return xxx_messageInfo_ZoneInfo.Size(m)
}
func (m *ZoneInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneInfo proto.InternalMessageInfo

func (m *ZoneInfo) GetUpperLeft() *LLPosition {
	if m != nil {
		return m.UpperLeft
	}
	return nil
}

func (m *ZoneInfo) GetBottomRight() *LLPosition {
	if m != nil {
		return m.BottomRight
	}
	return nil
}

// satellite information, including name and position
type SatelliteInfo struct {
	SatName              string       `protobuf:"bytes,1,opt,name=sat_name,json=satName,proto3" json:"sat_name,omitempty"`
	SatPosition          *LLAPosition `protobuf:"bytes,2,opt,name=sat_position,json=satPosition,proto3" json:"sat_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SatelliteInfo) Reset()         { *m = SatelliteInfo{} }
func (m *SatelliteInfo) String() string { return proto.CompactTextString(m) }
func (*SatelliteInfo) ProtoMessage()    {}
func (*SatelliteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{4}
}

func (m *SatelliteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatelliteInfo.Unmarshal(m, b)
}
func (m *SatelliteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatelliteInfo.Marshal(b, m, deterministic)
}
func (m *SatelliteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatelliteInfo.Merge(m, src)
}
func (m *SatelliteInfo) XXX_Size() int {
	return xxx_messageInfo_SatelliteInfo.Size(m)
}
func (m *SatelliteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SatelliteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SatelliteInfo proto.InternalMessageInfo

func (m *SatelliteInfo) GetSatName() string {
	if m != nil {
		return m.SatName
	}
	return ""
}

func (m *SatelliteInfo) GetSatPosition() *LLAPosition {
	if m != nil {
		return m.SatPosition
	}
	return nil
}

type SatRequest struct {
	SatInfo              *SatelliteInfo `protobuf:"bytes,1,opt,name=sat_info,json=satInfo,proto3" json:"sat_info,omitempty"`
	FindTarget           bool           `protobuf:"varint,2,opt,name=find_target,json=findTarget,proto3" json:"find_target,omitempty"`
	TargetInfo           []*TargetInfo  `protobuf:"bytes,3,rep,name=target_info,json=targetInfo,proto3" json:"target_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SatRequest) Reset()         { *m = SatRequest{} }
func (m *SatRequest) String() string { return proto.CompactTextString(m) }
func (*SatRequest) ProtoMessage()    {}
func (*SatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{5}
}

func (m *SatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatRequest.Unmarshal(m, b)
}
func (m *SatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatRequest.Marshal(b, m, deterministic)
}
func (m *SatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatRequest.Merge(m, src)
}
func (m *SatRequest) XXX_Size() int {
	return xxx_messageInfo_SatRequest.Size(m)
}
func (m *SatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SatRequest proto.InternalMessageInfo

func (m *SatRequest) GetSatInfo() *SatelliteInfo {
	if m != nil {
		return m.SatInfo
	}
	return nil
}

func (m *SatRequest) GetFindTarget() bool {
	if m != nil {
		return m.FindTarget
	}
	return false
}

func (m *SatRequest) GetTargetInfo() []*TargetInfo {
	if m != nil {
		return m.TargetInfo
	}
	return nil
}

type Base2Sat struct {
	BasePosition *LLPosition   `protobuf:"bytes,1,opt,name=base_position,json=basePosition,proto3" json:"base_position,omitempty"`
	FindTarget   bool          `protobuf:"varint,2,opt,name=find_target,json=findTarget,proto3" json:"find_target,omitempty"`
	TargetInfo   []*TargetInfo `protobuf:"bytes,3,rep,name=target_info,json=targetInfo,proto3" json:"target_info,omitempty"`
	// if this field is true, satellite takes the photo and call another rpc service
	TakePhoto            bool        `protobuf:"varint,4,opt,name=take_photo,json=takePhoto,proto3" json:"take_photo,omitempty"`
	Zone                 []*ZoneInfo `protobuf:"bytes,5,rep,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Base2Sat) Reset()         { *m = Base2Sat{} }
func (m *Base2Sat) String() string { return proto.CompactTextString(m) }
func (*Base2Sat) ProtoMessage()    {}
func (*Base2Sat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{6}
}

func (m *Base2Sat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Base2Sat.Unmarshal(m, b)
}
func (m *Base2Sat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Base2Sat.Marshal(b, m, deterministic)
}
func (m *Base2Sat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base2Sat.Merge(m, src)
}
func (m *Base2Sat) XXX_Size() int {
	return xxx_messageInfo_Base2Sat.Size(m)
}
func (m *Base2Sat) XXX_DiscardUnknown() {
	xxx_messageInfo_Base2Sat.DiscardUnknown(m)
}

var xxx_messageInfo_Base2Sat proto.InternalMessageInfo

func (m *Base2Sat) GetBasePosition() *LLPosition {
	if m != nil {
		return m.BasePosition
	}
	return nil
}

func (m *Base2Sat) GetFindTarget() bool {
	if m != nil {
		return m.FindTarget
	}
	return false
}

func (m *Base2Sat) GetTargetInfo() []*TargetInfo {
	if m != nil {
		return m.TargetInfo
	}
	return nil
}

func (m *Base2Sat) GetTakePhoto() bool {
	if m != nil {
		return m.TakePhoto
	}
	return false
}

func (m *Base2Sat) GetZone() []*ZoneInfo {
	if m != nil {
		return m.Zone
	}
	return nil
}

type SatPhotoRequest struct {
	Timestamp            string         `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SatInfo              *SatelliteInfo `protobuf:"bytes,2,opt,name=sat_info,json=satInfo,proto3" json:"sat_info,omitempty"`
	Zone                 []*ZoneInfo    `protobuf:"bytes,3,rep,name=zone,proto3" json:"zone,omitempty"`
	ImageData            []byte         `protobuf:"bytes,4,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SatPhotoRequest) Reset()         { *m = SatPhotoRequest{} }
func (m *SatPhotoRequest) String() string { return proto.CompactTextString(m) }
func (*SatPhotoRequest) ProtoMessage()    {}
func (*SatPhotoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{7}
}

func (m *SatPhotoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatPhotoRequest.Unmarshal(m, b)
}
func (m *SatPhotoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatPhotoRequest.Marshal(b, m, deterministic)
}
func (m *SatPhotoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatPhotoRequest.Merge(m, src)
}
func (m *SatPhotoRequest) XXX_Size() int {
	return xxx_messageInfo_SatPhotoRequest.Size(m)
}
func (m *SatPhotoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SatPhotoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SatPhotoRequest proto.InternalMessageInfo

func (m *SatPhotoRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *SatPhotoRequest) GetSatInfo() *SatelliteInfo {
	if m != nil {
		return m.SatInfo
	}
	return nil
}

func (m *SatPhotoRequest) GetZone() []*ZoneInfo {
	if m != nil {
		return m.Zone
	}
	return nil
}

func (m *SatPhotoRequest) GetImageData() []byte {
	if m != nil {
		return m.ImageData
	}
	return nil
}

type BasePhotoReceiveResponse struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReceivePhoto         bool     `protobuf:"varint,2,opt,name=receive_photo,json=receivePhoto,proto3" json:"receive_photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasePhotoReceiveResponse) Reset()         { *m = BasePhotoReceiveResponse{} }
func (m *BasePhotoReceiveResponse) String() string { return proto.CompactTextString(m) }
func (*BasePhotoReceiveResponse) ProtoMessage()    {}
func (*BasePhotoReceiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{8}
}

func (m *BasePhotoReceiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasePhotoReceiveResponse.Unmarshal(m, b)
}
func (m *BasePhotoReceiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasePhotoReceiveResponse.Marshal(b, m, deterministic)
}
func (m *BasePhotoReceiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasePhotoReceiveResponse.Merge(m, src)
}
func (m *BasePhotoReceiveResponse) XXX_Size() int {
	return xxx_messageInfo_BasePhotoReceiveResponse.Size(m)
}
func (m *BasePhotoReceiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BasePhotoReceiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BasePhotoReceiveResponse proto.InternalMessageInfo

func (m *BasePhotoReceiveResponse) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *BasePhotoReceiveResponse) GetReceivePhoto() bool {
	if m != nil {
		return m.ReceivePhoto
	}
	return false
}

type UnityRequest struct {
	StatusOk             bool     `protobuf:"varint,1,opt,name=status_ok,json=statusOk,proto3" json:"status_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnityRequest) Reset()         { *m = UnityRequest{} }
func (m *UnityRequest) String() string { return proto.CompactTextString(m) }
func (*UnityRequest) ProtoMessage()    {}
func (*UnityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{9}
}

func (m *UnityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnityRequest.Unmarshal(m, b)
}
func (m *UnityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnityRequest.Marshal(b, m, deterministic)
}
func (m *UnityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnityRequest.Merge(m, src)
}
func (m *UnityRequest) XXX_Size() int {
	return xxx_messageInfo_UnityRequest.Size(m)
}
func (m *UnityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnityRequest proto.InternalMessageInfo

func (m *UnityRequest) GetStatusOk() bool {
	if m != nil {
		return m.StatusOk
	}
	return false
}

type UnityRequestTemplate struct {
	FindTarget           bool          `protobuf:"varint,1,opt,name=find_target,json=findTarget,proto3" json:"find_target,omitempty"`
	TargetPosition       []*TargetInfo `protobuf:"bytes,2,rep,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnityRequestTemplate) Reset()         { *m = UnityRequestTemplate{} }
func (m *UnityRequestTemplate) String() string { return proto.CompactTextString(m) }
func (*UnityRequestTemplate) ProtoMessage()    {}
func (*UnityRequestTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{10}
}

func (m *UnityRequestTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnityRequestTemplate.Unmarshal(m, b)
}
func (m *UnityRequestTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnityRequestTemplate.Marshal(b, m, deterministic)
}
func (m *UnityRequestTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnityRequestTemplate.Merge(m, src)
}
func (m *UnityRequestTemplate) XXX_Size() int {
	return xxx_messageInfo_UnityRequestTemplate.Size(m)
}
func (m *UnityRequestTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_UnityRequestTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_UnityRequestTemplate proto.InternalMessageInfo

func (m *UnityRequestTemplate) GetFindTarget() bool {
	if m != nil {
		return m.FindTarget
	}
	return false
}

func (m *UnityRequestTemplate) GetTargetPosition() []*TargetInfo {
	if m != nil {
		return m.TargetPosition
	}
	return nil
}

type Base2Unity struct {
	FindTarget           bool             `protobuf:"varint,1,opt,name=find_target,json=findTarget,proto3" json:"find_target,omitempty"`
	TargetPosition       []*TargetInfo    `protobuf:"bytes,2,rep,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	TrackingSat          []*SatelliteInfo `protobuf:"bytes,3,rep,name=tracking_sat,json=trackingSat,proto3" json:"tracking_sat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Base2Unity) Reset()         { *m = Base2Unity{} }
func (m *Base2Unity) String() string { return proto.CompactTextString(m) }
func (*Base2Unity) ProtoMessage()    {}
func (*Base2Unity) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{11}
}

func (m *Base2Unity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Base2Unity.Unmarshal(m, b)
}
func (m *Base2Unity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Base2Unity.Marshal(b, m, deterministic)
}
func (m *Base2Unity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base2Unity.Merge(m, src)
}
func (m *Base2Unity) XXX_Size() int {
	return xxx_messageInfo_Base2Unity.Size(m)
}
func (m *Base2Unity) XXX_DiscardUnknown() {
	xxx_messageInfo_Base2Unity.DiscardUnknown(m)
}

var xxx_messageInfo_Base2Unity proto.InternalMessageInfo

func (m *Base2Unity) GetFindTarget() bool {
	if m != nil {
		return m.FindTarget
	}
	return false
}

func (m *Base2Unity) GetTargetPosition() []*TargetInfo {
	if m != nil {
		return m.TargetPosition
	}
	return nil
}

func (m *Base2Unity) GetTrackingSat() []*SatelliteInfo {
	if m != nil {
		return m.TrackingSat
	}
	return nil
}

type UnityPhotoRequest struct {
	Timestamp            string    `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Zone                 *ZoneInfo `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UnityPhotoRequest) Reset()         { *m = UnityPhotoRequest{} }
func (m *UnityPhotoRequest) String() string { return proto.CompactTextString(m) }
func (*UnityPhotoRequest) ProtoMessage()    {}
func (*UnityPhotoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{12}
}

func (m *UnityPhotoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnityPhotoRequest.Unmarshal(m, b)
}
func (m *UnityPhotoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnityPhotoRequest.Marshal(b, m, deterministic)
}
func (m *UnityPhotoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnityPhotoRequest.Merge(m, src)
}
func (m *UnityPhotoRequest) XXX_Size() int {
	return xxx_messageInfo_UnityPhotoRequest.Size(m)
}
func (m *UnityPhotoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnityPhotoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnityPhotoRequest proto.InternalMessageInfo

func (m *UnityPhotoRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *UnityPhotoRequest) GetZone() *ZoneInfo {
	if m != nil {
		return m.Zone
	}
	return nil
}

type BasePhotoResponse struct {
	Timestamp            string    `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Zone                 *ZoneInfo `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	ImageData            []byte    `protobuf:"bytes,3,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BasePhotoResponse) Reset()         { *m = BasePhotoResponse{} }
func (m *BasePhotoResponse) String() string { return proto.CompactTextString(m) }
func (*BasePhotoResponse) ProtoMessage()    {}
func (*BasePhotoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{13}
}

func (m *BasePhotoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasePhotoResponse.Unmarshal(m, b)
}
func (m *BasePhotoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasePhotoResponse.Marshal(b, m, deterministic)
}
func (m *BasePhotoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasePhotoResponse.Merge(m, src)
}
func (m *BasePhotoResponse) XXX_Size() int {
	return xxx_messageInfo_BasePhotoResponse.Size(m)
}
func (m *BasePhotoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BasePhotoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BasePhotoResponse proto.InternalMessageInfo

func (m *BasePhotoResponse) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *BasePhotoResponse) GetZone() *ZoneInfo {
	if m != nil {
		return m.Zone
	}
	return nil
}

func (m *BasePhotoResponse) GetImageData() []byte {
	if m != nil {
		return m.ImageData
	}
	return nil
}

func init() {
	proto.RegisterType((*LLPosition)(nil), "commu.LLPosition")
	proto.RegisterType((*LLAPosition)(nil), "commu.LLAPosition")
	proto.RegisterType((*TargetInfo)(nil), "commu.TargetInfo")
	proto.RegisterType((*ZoneInfo)(nil), "commu.ZoneInfo")
	proto.RegisterType((*SatelliteInfo)(nil), "commu.SatelliteInfo")
	proto.RegisterType((*SatRequest)(nil), "commu.SatRequest")
	proto.RegisterType((*Base2Sat)(nil), "commu.Base2Sat")
	proto.RegisterType((*SatPhotoRequest)(nil), "commu.SatPhotoRequest")
	proto.RegisterType((*BasePhotoReceiveResponse)(nil), "commu.BasePhotoReceiveResponse")
	proto.RegisterType((*UnityRequest)(nil), "commu.UnityRequest")
	proto.RegisterType((*UnityRequestTemplate)(nil), "commu.UnityRequest_template")
	proto.RegisterType((*Base2Unity)(nil), "commu.Base2Unity")
	proto.RegisterType((*UnityPhotoRequest)(nil), "commu.UnityPhotoRequest")
	proto.RegisterType((*BasePhotoResponse)(nil), "commu.BasePhotoResponse")
}

func init() {
	proto.RegisterFile("satcom.proto", fileDescriptor_a6b739bb65449003)
}

var fileDescriptor_a6b739bb65449003 = []byte{
	// 739 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5d, 0x4f, 0xdb, 0x58,
	0x10, 0x95, 0x63, 0x60, 0x93, 0x71, 0xb2, 0x6c, 0xee, 0x7e, 0x28, 0xb0, 0xac, 0x40, 0xe6, 0x05,
	0x69, 0x25, 0x88, 0xd2, 0xd2, 0xaa, 0xed, 0x53, 0xa1, 0xad, 0x54, 0x29, 0xa2, 0xc8, 0xe9, 0x87,
	0x84, 0x54, 0x59, 0x93, 0x70, 0x13, 0xdc, 0xd8, 0xbe, 0xae, 0xef, 0xa4, 0x52, 0xf9, 0x19, 0xfd,
	0x09, 0x55, 0xff, 0x53, 0x1f, 0xfa, 0x67, 0x2a, 0xdf, 0x7b, 0x1d, 0x9b, 0x90, 0x40, 0xfa, 0xc0,
	0x5b, 0x32, 0x99, 0x39, 0x67, 0xce, 0x9c, 0x63, 0x07, 0xea, 0x12, 0x69, 0x20, 0xa2, 0xfd, 0x24,
	0x15, 0x24, 0xd8, 0xea, 0x40, 0x44, 0xd1, 0xc4, 0x3d, 0x01, 0xe8, 0x76, 0x4f, 0x85, 0x0c, 0x28,
	0x10, 0x31, 0xdb, 0x82, 0x1a, 0x05, 0x11, 0x97, 0x84, 0x51, 0xd2, 0xb2, 0x76, 0xac, 0xbd, 0x9a,
	0x57, 0x14, 0xd8, 0x1f, 0x60, 0x87, 0x48, 0xad, 0xca, 0x8e, 0xb5, 0x57, 0xf1, 0xb2, 0x8f, 0xaa,
	0x12, 0x8f, 0x5a, 0xb6, 0xa9, 0xc4, 0x23, 0x17, 0xc1, 0xe9, 0x76, 0x9f, 0x2e, 0x0f, 0x88, 0xe1,
	0x14, 0x10, 0x43, 0xca, 0x29, 0xec, 0x6b, 0x14, 0x2b, 0x05, 0xc5, 0x07, 0x80, 0xd7, 0x98, 0x8e,
	0x38, 0xbd, 0x8c, 0x87, 0x82, 0x6d, 0x83, 0x43, 0xea, 0x9b, 0x1f, 0x63, 0xc4, 0x0d, 0x07, 0xe8,
	0xd2, 0x09, 0x46, 0x9c, 0x3d, 0x81, 0x75, 0xd3, 0x90, 0x98, 0xad, 0x14, 0xa1, 0xd3, 0x61, 0xfb,
	0xea, 0x04, 0xfb, 0xa5, 0x7d, 0xbd, 0xdf, 0x75, 0x6b, 0xfe, 0xdd, 0x4d, 0xa1, 0x7a, 0x26, 0x62,
	0xae, 0x98, 0xda, 0x00, 0x93, 0x24, 0xe1, 0xa9, 0x1f, 0xf2, 0x21, 0x19, 0x8c, 0xe6, 0x14, 0x63,
	0x0a, 0x51, 0x53, 0x4d, 0x5d, 0x3e, 0x24, 0x76, 0x1f, 0xea, 0x7d, 0x41, 0x24, 0x22, 0x3f, 0x0d,
	0x46, 0x17, 0x5a, 0xd6, 0xdc, 0x19, 0x47, 0xb7, 0x79, 0x59, 0x97, 0x8b, 0xd0, 0xe8, 0x21, 0xf1,
	0x30, 0x0c, 0x48, 0x13, 0x6f, 0x40, 0x55, 0xe2, 0x15, 0x7d, 0xbf, 0x49, 0xd4, 0xe2, 0x0e, 0x95,
	0xab, 0xcb, 0x28, 0x73, 0x24, 0x16, 0xb2, 0xbe, 0x58, 0x00, 0x3d, 0x24, 0x8f, 0x7f, 0x9c, 0x70,
	0x49, 0xec, 0x40, 0x13, 0x04, 0xf1, 0x50, 0x28, 0x02, 0xa7, 0xf3, 0x97, 0x41, 0xb8, 0xb2, 0x88,
	0xa2, 0xcd, 0x8f, 0x3e, 0x0c, 0xe2, 0x73, 0x5f, 0x5f, 0x4b, 0xb1, 0x56, 0x3d, 0xc8, 0x4a, 0xda,
	0x19, 0xd6, 0x99, 0xba, 0xa2, 0x40, 0xed, 0x1d, 0xbb, 0x24, 0xbc, 0x70, 0x2f, 0x37, 0x2a, 0xfb,
	0xec, 0xfe, 0xb0, 0xa0, 0x7a, 0x84, 0x92, 0x77, 0x7a, 0x48, 0xec, 0x01, 0x34, 0xfa, 0x28, 0x79,
	0xa1, 0xcc, 0x5a, 0x74, 0xbb, 0x7a, 0xd6, 0x37, 0x0d, 0xdc, 0x5d, 0x6c, 0xc6, 0xfe, 0x03, 0x20,
	0x1c, 0x73, 0x3f, 0xb9, 0x10, 0x24, 0x54, 0x14, 0xab, 0x5e, 0x2d, 0xab, 0x9c, 0x66, 0x05, 0xb6,
	0x0b, 0x2b, 0x97, 0x22, 0xe6, 0xad, 0x55, 0x85, 0xb5, 0x6e, 0xb0, 0xf2, 0xdc, 0x78, 0xea, 0x47,
	0xf7, 0x9b, 0x05, 0xeb, 0x3d, 0x24, 0x35, 0x91, 0xdf, 0xfd, 0xe6, 0xa7, 0xa3, 0xec, 0x4a, 0x65,
	0x19, 0x57, 0xf2, 0x3d, 0xec, 0x1b, 0xf6, 0xc8, 0xb4, 0x04, 0x11, 0x8e, 0xb8, 0x7f, 0x8e, 0x84,
	0x4a, 0x4b, 0xdd, 0xab, 0xa9, 0xca, 0x33, 0x24, 0x74, 0xdf, 0x43, 0x2b, 0xf3, 0xc0, 0xac, 0x39,
	0xe0, 0xc1, 0x27, 0xee, 0x71, 0x99, 0x88, 0x58, 0xf2, 0x5b, 0xd6, 0xdd, 0x85, 0x46, 0xaa, 0x07,
	0xcc, 0x9d, 0xf4, 0xed, 0xeb, 0xa6, 0xa8, 0x10, 0xdd, 0xff, 0xa1, 0xfe, 0x26, 0x0e, 0xe8, 0x73,
	0x7e, 0x81, 0x7f, 0xa1, 0x26, 0x09, 0x69, 0x22, 0x7d, 0x31, 0x56, 0x90, 0x55, 0xaf, 0xaa, 0x0b,
	0xaf, 0xc6, 0x2e, 0xc1, 0xdf, 0xe5, 0x66, 0x9f, 0x78, 0x94, 0x84, 0x48, 0x7c, 0xd6, 0x64, 0xeb,
	0x9a, 0xc9, 0x8f, 0xe7, 0x3d, 0xf3, 0x0b, 0x8c, 0x9e, 0x7d, 0xe4, 0xbf, 0x5a, 0x00, 0x2a, 0x86,
	0x8a, 0xfb, 0x4e, 0xb9, 0xd8, 0x43, 0xa8, 0x53, 0x8a, 0x83, 0x71, 0x10, 0x8f, 0x7c, 0xa9, 0xde,
	0x7b, 0xf6, 0x42, 0x9b, 0x9d, 0xbc, 0xb3, 0x87, 0xe4, 0xbe, 0x85, 0xa6, 0x5a, 0xef, 0x17, 0xe2,
	0x94, 0xa7, 0x43, 0x47, 0x69, 0x41, 0x4a, 0x27, 0xd0, 0x2c, 0xd9, 0xbf, 0xa4, 0xef, 0xb7, 0xe3,
	0xce, 0xa4, 0xce, 0x9e, 0x49, 0x5d, 0xe7, 0x7b, 0x05, 0xd6, 0x7a, 0x48, 0xc7, 0x22, 0x62, 0x87,
	0xe0, 0x1c, 0x67, 0x08, 0xef, 0x82, 0xcb, 0xec, 0x3d, 0xd0, 0x2c, 0x6e, 0x61, 0x64, 0x6e, 0xe6,
	0x14, 0xf9, 0xbb, 0x62, 0xcf, 0x6a, 0x5b, 0xec, 0x79, 0xf6, 0xa7, 0x60, 0x1e, 0x48, 0xc9, 0xfe,
	0x29, 0xa6, 0xca, 0x17, 0xda, 0xdc, 0x2e, 0x8d, 0xce, 0x8d, 0xf8, 0x29, 0x6c, 0x98, 0xd2, 0x8b,
	0x54, 0x44, 0xea, 0xc4, 0x45, 0xec, 0xb6, 0xcc, 0xf4, 0xdc, 0x50, 0x6e, 0x36, 0xcb, 0x6b, 0xa9,
	0x16, 0xb5, 0xd8, 0x23, 0x68, 0xe4, 0x7a, 0x74, 0xa0, 0xfe, 0x9c, 0x83, 0x32, 0x67, 0xb8, 0x6d,
	0xb1, 0x23, 0x80, 0x1e, 0x8f, 0xcf, 0x8d, 0xa6, 0x56, 0x79, 0xee, 0x8a, 0xaa, 0xd6, 0x75, 0x55,
	0x5a, 0x4e, 0xdb, 0x3a, 0x6a, 0x9c, 0x39, 0x92, 0x30, 0x0d, 0x83, 0x78, 0x7c, 0x90, 0xf4, 0xfb,
	0x6b, 0xea, 0xcf, 0xff, 0xde, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0xcc, 0x7f, 0xac, 0x0c,
	0x08, 0x00, 0x00,
}
