// Code generated by protoc-gen-go. DO NOT EDIT.
// source: satcom.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PositionInfo struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Alt                  float32  `protobuf:"fixed32,2,opt,name=alt,proto3" json:"alt,omitempty"`
	Lat                  float32  `protobuf:"fixed32,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,4,opt,name=lng,proto3" json:"lng,omitempty"`
	TargetName           string   `protobuf:"bytes,5,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionInfo) Reset()         { *m = PositionInfo{} }
func (m *PositionInfo) String() string { return proto.CompactTextString(m) }
func (*PositionInfo) ProtoMessage()    {}
func (*PositionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{0}
}

func (m *PositionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionInfo.Unmarshal(m, b)
}
func (m *PositionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionInfo.Marshal(b, m, deterministic)
}
func (m *PositionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionInfo.Merge(m, src)
}
func (m *PositionInfo) XXX_Size() int {
	return xxx_messageInfo_PositionInfo.Size(m)
}
func (m *PositionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PositionInfo proto.InternalMessageInfo

func (m *PositionInfo) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *PositionInfo) GetAlt() float32 {
	if m != nil {
		return m.Alt
	}
	return 0
}

func (m *PositionInfo) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *PositionInfo) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *PositionInfo) GetTargetName() string {
	if m != nil {
		return m.TargetName
	}
	return ""
}

type SatelliteInfo struct {
	SatName              string        `protobuf:"bytes,1,opt,name=sat_name,json=satName,proto3" json:"sat_name,omitempty"`
	SatPosition          *PositionInfo `protobuf:"bytes,2,opt,name=sat_position,json=satPosition,proto3" json:"sat_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SatelliteInfo) Reset()         { *m = SatelliteInfo{} }
func (m *SatelliteInfo) String() string { return proto.CompactTextString(m) }
func (*SatelliteInfo) ProtoMessage()    {}
func (*SatelliteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{1}
}

func (m *SatelliteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatelliteInfo.Unmarshal(m, b)
}
func (m *SatelliteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatelliteInfo.Marshal(b, m, deterministic)
}
func (m *SatelliteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatelliteInfo.Merge(m, src)
}
func (m *SatelliteInfo) XXX_Size() int {
	return xxx_messageInfo_SatelliteInfo.Size(m)
}
func (m *SatelliteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SatelliteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SatelliteInfo proto.InternalMessageInfo

func (m *SatelliteInfo) GetSatName() string {
	if m != nil {
		return m.SatName
	}
	return ""
}

func (m *SatelliteInfo) GetSatPosition() *PositionInfo {
	if m != nil {
		return m.SatPosition
	}
	return nil
}

type Sat2BaseInfo struct {
	SatName              string          `protobuf:"bytes,1,opt,name=sat_name,json=satName,proto3" json:"sat_name,omitempty"`
	SatPosition          *PositionInfo   `protobuf:"bytes,2,opt,name=sat_position,json=satPosition,proto3" json:"sat_position,omitempty"`
	FindTarget           bool            `protobuf:"varint,3,opt,name=find_target,json=findTarget,proto3" json:"find_target,omitempty"`
	TargetPosition       []*PositionInfo `protobuf:"bytes,4,rep,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Sat2BaseInfo) Reset()         { *m = Sat2BaseInfo{} }
func (m *Sat2BaseInfo) String() string { return proto.CompactTextString(m) }
func (*Sat2BaseInfo) ProtoMessage()    {}
func (*Sat2BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{2}
}

func (m *Sat2BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sat2BaseInfo.Unmarshal(m, b)
}
func (m *Sat2BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sat2BaseInfo.Marshal(b, m, deterministic)
}
func (m *Sat2BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sat2BaseInfo.Merge(m, src)
}
func (m *Sat2BaseInfo) XXX_Size() int {
	return xxx_messageInfo_Sat2BaseInfo.Size(m)
}
func (m *Sat2BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Sat2BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Sat2BaseInfo proto.InternalMessageInfo

func (m *Sat2BaseInfo) GetSatName() string {
	if m != nil {
		return m.SatName
	}
	return ""
}

func (m *Sat2BaseInfo) GetSatPosition() *PositionInfo {
	if m != nil {
		return m.SatPosition
	}
	return nil
}

func (m *Sat2BaseInfo) GetFindTarget() bool {
	if m != nil {
		return m.FindTarget
	}
	return false
}

func (m *Sat2BaseInfo) GetTargetPosition() []*PositionInfo {
	if m != nil {
		return m.TargetPosition
	}
	return nil
}

type Base2SatInfo struct {
	BasePosition         *PositionInfo   `protobuf:"bytes,1,opt,name=base_position,json=basePosition,proto3" json:"base_position,omitempty"`
	FindTarget           bool            `protobuf:"varint,2,opt,name=find_target,json=findTarget,proto3" json:"find_target,omitempty"`
	TargetPosition       []*PositionInfo `protobuf:"bytes,3,rep,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Base2SatInfo) Reset()         { *m = Base2SatInfo{} }
func (m *Base2SatInfo) String() string { return proto.CompactTextString(m) }
func (*Base2SatInfo) ProtoMessage()    {}
func (*Base2SatInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{3}
}

func (m *Base2SatInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Base2SatInfo.Unmarshal(m, b)
}
func (m *Base2SatInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Base2SatInfo.Marshal(b, m, deterministic)
}
func (m *Base2SatInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base2SatInfo.Merge(m, src)
}
func (m *Base2SatInfo) XXX_Size() int {
	return xxx_messageInfo_Base2SatInfo.Size(m)
}
func (m *Base2SatInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Base2SatInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Base2SatInfo proto.InternalMessageInfo

func (m *Base2SatInfo) GetBasePosition() *PositionInfo {
	if m != nil {
		return m.BasePosition
	}
	return nil
}

func (m *Base2SatInfo) GetFindTarget() bool {
	if m != nil {
		return m.FindTarget
	}
	return false
}

func (m *Base2SatInfo) GetTargetPosition() []*PositionInfo {
	if m != nil {
		return m.TargetPosition
	}
	return nil
}

type Unity2BaseInfo struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unity2BaseInfo) Reset()         { *m = Unity2BaseInfo{} }
func (m *Unity2BaseInfo) String() string { return proto.CompactTextString(m) }
func (*Unity2BaseInfo) ProtoMessage()    {}
func (*Unity2BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{4}
}

func (m *Unity2BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unity2BaseInfo.Unmarshal(m, b)
}
func (m *Unity2BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unity2BaseInfo.Marshal(b, m, deterministic)
}
func (m *Unity2BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unity2BaseInfo.Merge(m, src)
}
func (m *Unity2BaseInfo) XXX_Size() int {
	return xxx_messageInfo_Unity2BaseInfo.Size(m)
}
func (m *Unity2BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Unity2BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Unity2BaseInfo proto.InternalMessageInfo

func (m *Unity2BaseInfo) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Unity2BaseInfoTemplate struct {
	FindTarget           bool            `protobuf:"varint,1,opt,name=find_target,json=findTarget,proto3" json:"find_target,omitempty"`
	TargetPosition       []*PositionInfo `protobuf:"bytes,2,rep,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Unity2BaseInfoTemplate) Reset()         { *m = Unity2BaseInfoTemplate{} }
func (m *Unity2BaseInfoTemplate) String() string { return proto.CompactTextString(m) }
func (*Unity2BaseInfoTemplate) ProtoMessage()    {}
func (*Unity2BaseInfoTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{5}
}

func (m *Unity2BaseInfoTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unity2BaseInfoTemplate.Unmarshal(m, b)
}
func (m *Unity2BaseInfoTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unity2BaseInfoTemplate.Marshal(b, m, deterministic)
}
func (m *Unity2BaseInfoTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unity2BaseInfoTemplate.Merge(m, src)
}
func (m *Unity2BaseInfoTemplate) XXX_Size() int {
	return xxx_messageInfo_Unity2BaseInfoTemplate.Size(m)
}
func (m *Unity2BaseInfoTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_Unity2BaseInfoTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_Unity2BaseInfoTemplate proto.InternalMessageInfo

func (m *Unity2BaseInfoTemplate) GetFindTarget() bool {
	if m != nil {
		return m.FindTarget
	}
	return false
}

func (m *Unity2BaseInfoTemplate) GetTargetPosition() []*PositionInfo {
	if m != nil {
		return m.TargetPosition
	}
	return nil
}

type Base2UnityInfo struct {
	FindTarget           bool             `protobuf:"varint,1,opt,name=find_target,json=findTarget,proto3" json:"find_target,omitempty"`
	TargetPosition       []*PositionInfo  `protobuf:"bytes,2,rep,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	TrackingSat          []*SatelliteInfo `protobuf:"bytes,3,rep,name=tracking_sat,json=trackingSat,proto3" json:"tracking_sat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Base2UnityInfo) Reset()         { *m = Base2UnityInfo{} }
func (m *Base2UnityInfo) String() string { return proto.CompactTextString(m) }
func (*Base2UnityInfo) ProtoMessage()    {}
func (*Base2UnityInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6b739bb65449003, []int{6}
}

func (m *Base2UnityInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Base2UnityInfo.Unmarshal(m, b)
}
func (m *Base2UnityInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Base2UnityInfo.Marshal(b, m, deterministic)
}
func (m *Base2UnityInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base2UnityInfo.Merge(m, src)
}
func (m *Base2UnityInfo) XXX_Size() int {
	return xxx_messageInfo_Base2UnityInfo.Size(m)
}
func (m *Base2UnityInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Base2UnityInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Base2UnityInfo proto.InternalMessageInfo

func (m *Base2UnityInfo) GetFindTarget() bool {
	if m != nil {
		return m.FindTarget
	}
	return false
}

func (m *Base2UnityInfo) GetTargetPosition() []*PositionInfo {
	if m != nil {
		return m.TargetPosition
	}
	return nil
}

func (m *Base2UnityInfo) GetTrackingSat() []*SatelliteInfo {
	if m != nil {
		return m.TrackingSat
	}
	return nil
}

func init() {
	proto.RegisterType((*PositionInfo)(nil), "commu.PositionInfo")
	proto.RegisterType((*SatelliteInfo)(nil), "commu.SatelliteInfo")
	proto.RegisterType((*Sat2BaseInfo)(nil), "commu.Sat2BaseInfo")
	proto.RegisterType((*Base2SatInfo)(nil), "commu.Base2SatInfo")
	proto.RegisterType((*Unity2BaseInfo)(nil), "commu.Unity2BaseInfo")
	proto.RegisterType((*Unity2BaseInfoTemplate)(nil), "commu.Unity2BaseInfo_template")
	proto.RegisterType((*Base2UnityInfo)(nil), "commu.Base2UnityInfo")
}

func init() {
	proto.RegisterFile("satcom.proto", fileDescriptor_a6b739bb65449003)
}

var fileDescriptor_a6b739bb65449003 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x65, 0x9a, 0xdd, 0x75, 0xf7, 0x26, 0xad, 0xcb, 0xac, 0x62, 0x76, 0x11, 0x2d, 0x79, 0xea,
	0x53, 0x95, 0x0a, 0x2a, 0xa8, 0x2f, 0xbb, 0x20, 0xf8, 0x22, 0x92, 0xac, 0x0a, 0xbe, 0x84, 0xdb,
	0xee, 0x6c, 0x18, 0x36, 0x33, 0x13, 0x32, 0x57, 0x51, 0x5f, 0xfd, 0x18, 0xfd, 0x0c, 0x3f, 0xc4,
	0x8f, 0x91, 0x99, 0xa4, 0x49, 0x2b, 0x16, 0xfa, 0xd2, 0xb7, 0xe1, 0x70, 0xee, 0xb9, 0xe7, 0x9c,
	0xde, 0x06, 0x22, 0x8b, 0xb4, 0x30, 0x6a, 0x5a, 0xd5, 0x86, 0x0c, 0xdf, 0x5f, 0x18, 0xa5, 0x3e,
	0x27, 0x3f, 0x18, 0x44, 0xef, 0x8c, 0x95, 0x24, 0x8d, 0x7e, 0xa3, 0xaf, 0x0d, 0xbf, 0x0f, 0x47,
	0x24, 0x95, 0xb0, 0x84, 0xaa, 0x8a, 0xd9, 0x98, 0x4d, 0x8e, 0xd2, 0x1e, 0xe0, 0xc7, 0x10, 0x60,
	0x49, 0xf1, 0x60, 0xcc, 0x26, 0x83, 0xd4, 0x3d, 0x1d, 0x52, 0x22, 0xc5, 0x41, 0x83, 0x94, 0xd8,
	0x20, 0xba, 0x88, 0xf7, 0x5a, 0x44, 0x17, 0xfc, 0x21, 0x84, 0x84, 0x75, 0x21, 0x28, 0xd7, 0xa8,
	0x44, 0xbc, 0xef, 0x55, 0xa1, 0x81, 0xde, 0xa2, 0x12, 0xc9, 0x1c, 0x86, 0x19, 0x92, 0x28, 0x4b,
	0x49, 0xc2, 0xbb, 0x38, 0x85, 0x43, 0x8b, 0x2d, 0xbd, 0x31, 0x71, 0xcb, 0xa2, 0xe7, 0xf2, 0xa7,
	0x3e, 0x48, 0x5e, 0xb5, 0xa6, 0xbd, 0x97, 0x70, 0x76, 0x32, 0xf5, 0x79, 0xa6, 0xab, 0x59, 0xd2,
	0xd0, 0x22, 0x2d, 0x81, 0xe4, 0x37, 0x83, 0x28, 0x43, 0x9a, 0x9d, 0xa3, 0xdd, 0xd5, 0x0e, 0x17,
	0xf4, 0x5a, 0xea, 0xab, 0xbc, 0x89, 0xe6, 0x4b, 0x39, 0x4c, 0xc1, 0x41, 0x97, 0x1e, 0xe1, 0x2f,
	0xe1, 0x76, 0xdb, 0x44, 0xa7, 0xbd, 0x37, 0x0e, 0x36, 0x69, 0x8f, 0x1a, 0x6e, 0x17, 0xe1, 0x27,
	0x83, 0xc8, 0xd9, 0x9f, 0x65, 0x48, 0x3e, 0xc2, 0x73, 0x18, 0xce, 0xd1, 0x8a, 0x5e, 0x8c, 0x6d,
	0x36, 0x1a, 0x39, 0xe6, 0x26, 0xa7, 0x83, 0x6d, 0x9c, 0x06, 0xdb, 0x3b, 0x4d, 0x60, 0xf4, 0x5e,
	0x4b, 0xfa, 0xd6, 0xb7, 0x7d, 0x0c, 0x81, 0xb2, 0x45, 0x5b, 0xb4, 0x7b, 0x26, 0x5f, 0xe1, 0xde,
	0x3a, 0x27, 0x27, 0xa1, 0xaa, 0x12, 0x49, 0xfc, 0xeb, 0x8e, 0x6d, 0xe3, 0x6e, 0xb0, 0xbd, 0xbb,
	0x5f, 0x0c, 0x46, 0xbe, 0x47, 0xbf, 0xdf, 0xdb, 0xdb, 0xed, 0x46, 0xfe, 0x0c, 0x22, 0xaa, 0x71,
	0x71, 0x23, 0x75, 0x91, 0x5b, 0xff, 0x77, 0x71, 0xa3, 0x77, 0xda, 0xd1, 0xb5, 0xdb, 0x4f, 0xc3,
	0x25, 0xd3, 0x5d, 0xeb, 0x1f, 0x06, 0x07, 0x19, 0xd2, 0x85, 0x51, 0xfc, 0x05, 0x84, 0x17, 0x8e,
	0xfe, 0x51, 0x7e, 0xcf, 0x90, 0xf8, 0x49, 0x3f, 0xdc, 0x35, 0x78, 0xb6, 0x04, 0x57, 0xaf, 0x64,
	0xc2, 0x1e, 0x33, 0xfe, 0x01, 0x4e, 0x53, 0xb1, 0x10, 0xf2, 0x8b, 0x78, 0x5d, 0x1b, 0xe5, 0x73,
	0xf7, 0x75, 0x3f, 0x68, 0xa7, 0x36, 0xfc, 0x1c, 0x67, 0x77, 0x57, 0x55, 0xbb, 0xce, 0xbc, 0xee,
	0x2b, 0x08, 0x33, 0xa1, 0xaf, 0x2e, 0x8d, 0x87, 0xf9, 0xff, 0x99, 0x9d, 0xc0, 0xfa, 0x82, 0x09,
	0x3b, 0x1f, 0x7e, 0x0a, 0x2d, 0x61, 0x5d, 0x4a, 0x7d, 0xf3, 0xa8, 0x9a, 0xcf, 0x0f, 0xfc, 0xb7,
	0xe9, 0xc9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x05, 0xf3, 0xea, 0xab, 0x04, 0x00, 0x00,
}
