// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/satsys.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac7433c1c06b74f0, []int{0}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateContext struct {
	SysName              string   `protobuf:"bytes,1,opt,name=sys_name,json=sysName,proto3" json:"sys_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContext) Reset()         { *m = UpdateContext{} }
func (m *UpdateContext) String() string { return proto.CompactTextString(m) }
func (*UpdateContext) ProtoMessage()    {}
func (*UpdateContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac7433c1c06b74f0, []int{1}
}

func (m *UpdateContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContext.Unmarshal(m, b)
}
func (m *UpdateContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContext.Marshal(b, m, deterministic)
}
func (m *UpdateContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContext.Merge(m, src)
}
func (m *UpdateContext) XXX_Size() int {
	return xxx_messageInfo_UpdateContext.Size(m)
}
func (m *UpdateContext) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContext.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContext proto.InternalMessageInfo

func (m *UpdateContext) GetSysName() string {
	if m != nil {
		return m.SysName
	}
	return ""
}

type SearchContext struct {
	SysName              string   `protobuf:"bytes,1,opt,name=sys_name,json=sysName,proto3" json:"sys_name,omitempty"`
	SatName              string   `protobuf:"bytes,2,opt,name=sat_name,json=satName,proto3" json:"sat_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchContext) Reset()         { *m = SearchContext{} }
func (m *SearchContext) String() string { return proto.CompactTextString(m) }
func (*SearchContext) ProtoMessage()    {}
func (*SearchContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac7433c1c06b74f0, []int{2}
}

func (m *SearchContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchContext.Unmarshal(m, b)
}
func (m *SearchContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchContext.Marshal(b, m, deterministic)
}
func (m *SearchContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchContext.Merge(m, src)
}
func (m *SearchContext) XXX_Size() int {
	return xxx_messageInfo_SearchContext.Size(m)
}
func (m *SearchContext) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchContext.DiscardUnknown(m)
}

var xxx_messageInfo_SearchContext proto.InternalMessageInfo

func (m *SearchContext) GetSysName() string {
	if m != nil {
		return m.SysName
	}
	return ""
}

func (m *SearchContext) GetSatName() string {
	if m != nil {
		return m.SatName
	}
	return ""
}

type Satellite struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumSat               string   `protobuf:"bytes,2,opt,name=num_sat,json=numSat,proto3" json:"num_sat,omitempty"`
	Inter                string   `protobuf:"bytes,3,opt,name=inter,proto3" json:"inter,omitempty"`
	Year                 string   `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
	Day                  string   `protobuf:"bytes,5,opt,name=day,proto3" json:"day,omitempty"`
	FirstMotion          string   `protobuf:"bytes,6,opt,name=first_motion,json=firstMotion,proto3" json:"first_motion,omitempty"`
	SecondMotion         string   `protobuf:"bytes,7,opt,name=second_motion,json=secondMotion,proto3" json:"second_motion,omitempty"`
	Drag                 string   `protobuf:"bytes,8,opt,name=drag,proto3" json:"drag,omitempty"`
	Number               string   `protobuf:"bytes,9,opt,name=number,proto3" json:"number,omitempty"`
	Incl                 string   `protobuf:"bytes,10,opt,name=incl,proto3" json:"incl,omitempty"`
	RA                   string   `protobuf:"bytes,11,opt,name=r_a,json=rA,proto3" json:"r_a,omitempty"`
	Eccentricity         string   `protobuf:"bytes,12,opt,name=eccentricity,proto3" json:"eccentricity,omitempty"`
	ArgPer               string   `protobuf:"bytes,13,opt,name=arg_per,json=argPer,proto3" json:"arg_per,omitempty"`
	Anomaly              string   `protobuf:"bytes,14,opt,name=anomaly,proto3" json:"anomaly,omitempty"`
	Motion               string   `protobuf:"bytes,15,opt,name=motion,proto3" json:"motion,omitempty"`
	Epoch                string   `protobuf:"bytes,16,opt,name=epoch,proto3" json:"epoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Satellite) Reset()         { *m = Satellite{} }
func (m *Satellite) String() string { return proto.CompactTextString(m) }
func (*Satellite) ProtoMessage()    {}
func (*Satellite) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac7433c1c06b74f0, []int{3}
}

func (m *Satellite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Satellite.Unmarshal(m, b)
}
func (m *Satellite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Satellite.Marshal(b, m, deterministic)
}
func (m *Satellite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Satellite.Merge(m, src)
}
func (m *Satellite) XXX_Size() int {
	return xxx_messageInfo_Satellite.Size(m)
}
func (m *Satellite) XXX_DiscardUnknown() {
	xxx_messageInfo_Satellite.DiscardUnknown(m)
}

var xxx_messageInfo_Satellite proto.InternalMessageInfo

func (m *Satellite) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Satellite) GetNumSat() string {
	if m != nil {
		return m.NumSat
	}
	return ""
}

func (m *Satellite) GetInter() string {
	if m != nil {
		return m.Inter
	}
	return ""
}

func (m *Satellite) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *Satellite) GetDay() string {
	if m != nil {
		return m.Day
	}
	return ""
}

func (m *Satellite) GetFirstMotion() string {
	if m != nil {
		return m.FirstMotion
	}
	return ""
}

func (m *Satellite) GetSecondMotion() string {
	if m != nil {
		return m.SecondMotion
	}
	return ""
}

func (m *Satellite) GetDrag() string {
	if m != nil {
		return m.Drag
	}
	return ""
}

func (m *Satellite) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Satellite) GetIncl() string {
	if m != nil {
		return m.Incl
	}
	return ""
}

func (m *Satellite) GetRA() string {
	if m != nil {
		return m.RA
	}
	return ""
}

func (m *Satellite) GetEccentricity() string {
	if m != nil {
		return m.Eccentricity
	}
	return ""
}

func (m *Satellite) GetArgPer() string {
	if m != nil {
		return m.ArgPer
	}
	return ""
}

func (m *Satellite) GetAnomaly() string {
	if m != nil {
		return m.Anomaly
	}
	return ""
}

func (m *Satellite) GetMotion() string {
	if m != nil {
		return m.Motion
	}
	return ""
}

func (m *Satellite) GetEpoch() string {
	if m != nil {
		return m.Epoch
	}
	return ""
}

type Satellite_System struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Satellite_System) Reset()         { *m = Satellite_System{} }
func (m *Satellite_System) String() string { return proto.CompactTextString(m) }
func (*Satellite_System) ProtoMessage()    {}
func (*Satellite_System) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac7433c1c06b74f0, []int{4}
}

func (m *Satellite_System) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Satellite_System.Unmarshal(m, b)
}
func (m *Satellite_System) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Satellite_System.Marshal(b, m, deterministic)
}
func (m *Satellite_System) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Satellite_System.Merge(m, src)
}
func (m *Satellite_System) XXX_Size() int {
	return xxx_messageInfo_Satellite_System.Size(m)
}
func (m *Satellite_System) XXX_DiscardUnknown() {
	xxx_messageInfo_Satellite_System.DiscardUnknown(m)
}

var xxx_messageInfo_Satellite_System proto.InternalMessageInfo

func (m *Satellite_System) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateResponse)(nil), "satsys.UpdateResponse")
	proto.RegisterType((*UpdateContext)(nil), "satsys.UpdateContext")
	proto.RegisterType((*SearchContext)(nil), "satsys.SearchContext")
	proto.RegisterType((*Satellite)(nil), "satsys.Satellite")
	proto.RegisterType((*Satellite_System)(nil), "satsys.Satellite_System")
}

func init() {
	proto.RegisterFile("pb/satsys.proto", fileDescriptor_ac7433c1c06b74f0)
}

var fileDescriptor_ac7433c1c06b74f0 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x6d, 0x9a, 0x34, 0x69, 0x26, 0x76, 0x13, 0x56, 0x50, 0x96, 0x9e, 0xc0, 0x48, 0x08, 0xf5,
	0xd0, 0x4a, 0x70, 0xe4, 0x80, 0x00, 0x21, 0x4e, 0x20, 0x54, 0x8b, 0x0b, 0x17, 0x6b, 0xec, 0x0c,
	0xa9, 0x85, 0xbd, 0xb6, 0x76, 0xa6, 0x12, 0xfb, 0x03, 0x7c, 0x00, 0x5f, 0x8c, 0x76, 0xd7, 0xb1,
	0x1a, 0x09, 0x89, 0xdb, 0xbc, 0x37, 0x6f, 0x76, 0xc6, 0x33, 0xcf, 0xb0, 0xee, 0xcb, 0x6b, 0x46,
	0x61, 0xc7, 0x57, 0xbd, 0xed, 0xa4, 0x53, 0xf3, 0x88, 0xb2, 0x4b, 0x38, 0xfb, 0xd6, 0x6f, 0x51,
	0xe8, 0x86, 0xb8, 0xef, 0x0c, 0x93, 0xd2, 0xb0, 0x68, 0x89, 0x19, 0x77, 0xa4, 0x27, 0x4f, 0x27,
	0x2f, 0x97, 0x37, 0x7b, 0x98, 0x5d, 0x42, 0x1a, 0xb5, 0x1f, 0x3a, 0x23, 0xf4, 0x4b, 0xd4, 0x13,
	0x38, 0x65, 0xc7, 0x85, 0xc1, 0x76, 0xd4, 0xb2, 0xe3, 0x2f, 0xd8, 0x52, 0xf6, 0x11, 0xd2, 0x9c,
	0xd0, 0x56, 0xb7, 0xff, 0xd7, 0x86, 0x14, 0x4a, 0x4c, 0x1d, 0x0f, 0x29, 0x94, 0xf0, 0xcc, 0x9f,
	0x29, 0x2c, 0x73, 0x14, 0x6a, 0x9a, 0x5a, 0x48, 0x29, 0x98, 0xdd, 0xab, 0x0f, 0xb1, 0x7a, 0x0c,
	0x0b, 0x73, 0xd7, 0x16, 0x8c, 0x32, 0xd4, 0xce, 0xcd, 0x5d, 0x9b, 0xa3, 0xa8, 0x87, 0x70, 0x52,
	0x1b, 0x21, 0xab, 0xa7, 0x81, 0x8e, 0xc0, 0x3f, 0xe1, 0x08, 0xad, 0x9e, 0xc5, 0x27, 0x7c, 0xac,
	0x36, 0x30, 0xdd, 0xa2, 0xd3, 0x27, 0x81, 0xf2, 0xa1, 0x7a, 0x06, 0xc9, 0x8f, 0xda, 0xb2, 0x14,
	0x6d, 0x27, 0x75, 0x67, 0xf4, 0x3c, 0xa4, 0x56, 0x81, 0xfb, 0x1c, 0x28, 0xf5, 0x1c, 0x52, 0xa6,
	0xaa, 0x33, 0xdb, 0xbd, 0x66, 0x11, 0x34, 0x49, 0x24, 0x07, 0x91, 0x82, 0xd9, 0xd6, 0xe2, 0x4e,
	0x9f, 0xc6, 0x6e, 0x3e, 0x56, 0xe7, 0xe0, 0x27, 0x2c, 0xc9, 0xea, 0xe5, 0x38, 0x6f, 0x19, 0x27,
	0xab, 0x4d, 0xd5, 0x68, 0x88, 0x5a, 0x1f, 0xab, 0x35, 0x4c, 0x6d, 0x81, 0x7a, 0x15, 0xa8, 0x63,
	0xfb, 0x4e, 0x65, 0x90, 0x50, 0x55, 0x91, 0x11, 0x5b, 0x57, 0xb5, 0x38, 0x9d, 0xc4, 0xa6, 0xf7,
	0x39, 0xbf, 0x11, 0xb4, 0xbb, 0xa2, 0x27, 0xab, 0xd3, 0xd8, 0x01, 0xed, 0xee, 0x2b, 0x59, 0x7f,
	0x59, 0x34, 0x5d, 0x8b, 0x8d, 0xd3, 0x67, 0x71, 0xcd, 0x03, 0xf4, 0x33, 0x0d, 0x5f, 0xb1, 0x8e,
	0x15, 0x11, 0xf9, 0x1d, 0x52, 0xdf, 0x55, 0xb7, 0x7a, 0x13, 0x77, 0x18, 0x40, 0xf6, 0x02, 0x36,
	0xe3, 0x4d, 0x8a, 0xdc, 0xb1, 0x50, 0xfb, 0xaf, 0xd3, 0xbc, 0xfa, 0x3d, 0x81, 0x79, 0x8e, 0x92,
	0x3b, 0x56, 0x6f, 0x20, 0xfd, 0x44, 0x32, 0x56, 0xb1, 0x7a, 0x74, 0x35, 0xd8, 0xf1, 0xc0, 0x25,
	0x17, 0x0f, 0x46, 0x7a, 0x2f, 0xcd, 0x8e, 0xd4, 0x5b, 0x48, 0xa2, 0xef, 0x86, 0x5e, 0x63, 0xed,
	0x81, 0x1b, 0x2f, 0xce, 0x0f, 0xe9, 0xbd, 0xa1, 0xb3, 0xa3, 0xf7, 0xe9, 0xf7, 0x15, 0x0b, 0xda,
	0xa6, 0x36, 0x3f, 0xaf, 0xfb, 0xb2, 0x9c, 0x87, 0x5f, 0xe0, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x72, 0x39, 0x98, 0xef, 0x15, 0x03, 0x00, 0x00,
}
